data_source postgres_youtube:
  type: postgres
  connection:
    host: ${POSTGRES_CONN_HOST}
    port: ${POSTGRES_CONN_PORT}
    username: ${ELT_DATABASE_USERNAME}
    password: ${ELT_DATABASE_PASSWORD}
    database: ${ELT_DATABASE_NAME}
