name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_CONN_HOST: ${{ secrets.POSTGRES_CONN_HOST }}
      POSTGRES_CONN_PORT: ${{ secrets.POSTGRES_CONN_PORT }}
      ELT_DATABASE_USERNAME: ${{ secrets.ELT_DATABASE_USERNAME }}
      ELT_DATABASE_PASSWORD: ${{ secrets.ELT_DATABASE_PASSWORD }}
      ELT_DATABASE_NAME: ${{ secrets.ELT_DATABASE_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Prepare Soda Core configs
        run: |
          mkdir -p $GITHUB_WORKSPACE/include/quality
          cp -n include/quality/* $GITHUB_WORKSPACE/include/quality/ || true

      - name: Initialize Airflow for tests
        run: |
          export AIRFLOW_HOME=$(pwd)/airflow_home
          mkdir -p $AIRFLOW_HOME
          airflow db init
          export PYTHONPATH=$PYTHONPATH:$(pwd)

      - name: Run tests
        run: |
          pytest tests/ -v -s
